### ISSUE TITLE
unable to start markserv (Error Module did not self-register.)

### ISSUE THREAD

**Issue by sujee** [F1LT3R/markserv#15]
I get this following error.

$ markserv
/usr/lib/node_modules/markserv/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at bindings (/usr/lib/node_modules/markserv/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/usr/lib/node_modules/markserv/node_modules/jsdom/node_modules/contextify/lib/contextify.js:1:96)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)

**Comment by F1LT3R** [comment]
Hi @sujee, thanks for sharing the issue you discovered.

I just uninstalled and re-installed `markserv` quickly here to check it was working. It does work for me. (I'm on OSX.)

- What OS are you using?
- Which version of Node are you using?
- How did you install Node? (Package manager, homebrew, apt-get, etc)
