### ISSUE TITLE
error during startup

### ISSUE THREAD

**Issue by sujee** [F1LT3R/markserv#22]
Env
Red Hat Enterprise Linux Server release 7.2 (Maipo)

$ node -v --> v6.2.2

installed markserv as follows
   $ sudo npm install -g markserv

when starting, I get the following error:
 $  markserv
/usr/lib/node_modules/markserv/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at bindings (/usr/lib/node_modules/markserv/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/usr/lib/node_modules/markserv/node_modules/jsdom/node_modules/contextify/lib/contextify.js:1:96)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)

**Comment by F1LT3R** [comment]
I will try this tonight. Thanks for the feedback.

**Comment by F1LT3R** [comment]
I did look into this over the weekend. With Red Hat being enterprise, I didn't get time to finish the process of setting up the VM (network issues). So I might try downloading CentOS and try that first as it may have a similar issue.

**Comment by sujee** [comment]
I can give you access to the test vm in cloud I have been using.
Please contact me off line.
Thx

http://sujee.net (sent from mobile...)

**Comment by F1LT3R** [comment]
I did run CentOS and install Node. Markserv worked fine with latest node. I notice you are on v6?

I think I see what is the issue though. I will try and update that for you some time in the week.

**Comment by F1LT3R** [comment]
Hi @sujee could you try uninstalling and re-installing markserv and let me know if things are working?

```shell
npm uninstall -g markserv
npm install -g markserv
```

**Comment by sujee** [comment]
brilliant !
that worked !!
thanks so much for chasing this down.  Much appreciate your effort.

Sujee Maniyam (http://sujee.net | http://www.linkedin.com/in/sujeemaniyam )

**Comment by F1LT3R** [comment]
NP. Glad it worked!

We have @laurencer to thank for spotting this:  https://github.com/F1LT3R/markserv/pull/14
